### ISSUE TITLE
can't access docker macvlan container with split-vpn

### ISSUE THREAD

**Issue by rjcds** [peacey/split-vpn#55]
I have a docker container with the following network

```
version: "2.3"
services:
   ...
    networks:
      macvlan0:
        ipv4_address: 192.168.1.245
    restart: unless-stopped

networks:
  macvlan0:
    name: macvlan0
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
```

Then in my vpn.conf I have

` FORCED_SOURCE_IPV4="192.168.1.245/32" `

Which works very well

The container (192.168.1.245) is reachable from within my home network. 

However when I log in via a VPN (either wireguard or UDM's LT2P), the container is unreachable

I've tried to put in some of the routing rules as suggested [here](https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/), but this breaks split-VPN...

Any pointers on how to route so I can still reach the container from an incoming VPN ?
